os: linux
dist: bionic
language: php
php: "7.4"
services: postgresql

before_script:
  - psql -c "CREATE DATABASE pulse;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'pulse';" -U postgres
  - cd implementacao
  - cp .env.travis .env
  - composer install
  - php artisan migrate:refresh
script:
  - make test
