version: '3'
services:
  nginx:
    image: dkimg/nginx:1.18.0
    container_name: pulse_nginx
    restart: unless-stopped
    tty: true
    links:
      - app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage/logs/:/var/log/nginx
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - pulse-network
  app:
    image: dkimg/php:7.4
    container_name: pulse_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    expose:
      - "9000"
    links:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - pulse-network
  db:
    image: postgres:12.0-alpine
    container_name: pulse_db
    restart: always
    tty: true
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pulse
    networks:
      - pulse-network
  adminer:
    image: adminer:4.7.7-standalone
    container_name: pulse_adminer
    restart: always
    links:
      - db
    networks:
      - pulse-network
networks:
  pulse-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
