/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDRADE
 */
public class Frmmenu extends javax.swing.JFrame {

    /**
     * Creates new form Frmmenu
     */
    public Frmmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_cliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_usuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_fornecedores = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        menu_consulta_produtos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menu_ponto_penda = new javax.swing.JMenuItem();
        menu_posicao_dia = new javax.swing.JMenuItem();
        menu_relatorio_vendas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menu_troca_usuarios = new javax.swing.JMenuItem();
        menu_sair = new javax.swing.JMenu();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jMenu1.setText("Clientes");

        menu_cliente.setText("Controle de Clientes");
        menu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuários");

        menu_usuarios.setText("Controle de Usuário");
        menu_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_usuariosActionPerformed(evt);
            }
        });
        jMenu2.add(menu_usuarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fornecedores");

        menu_fornecedores.setText("Controle de Fornecedores");
        menu_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fornecedoresActionPerformed(evt);
            }
        });
        jMenu3.add(menu_fornecedores);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Produtos");

        jMenuItem5.setText("Controle de Estoque");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        menu_consulta_produtos.setText("Consulta de Produtos");
        menu_consulta_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consulta_produtosActionPerformed(evt);
            }
        });
        jMenu4.add(menu_consulta_produtos);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Vendas");

        menu_ponto_penda.setText("Abrir PDV");
        menu_ponto_penda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ponto_pendaActionPerformed(evt);
            }
        });
        jMenu6.add(menu_ponto_penda);

        menu_posicao_dia.setText("Posição do Dia");
        menu_posicao_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_posicao_diaActionPerformed(evt);
            }
        });
        jMenu6.add(menu_posicao_dia);

        menu_relatorio_vendas.setText("Relatório de Venas");
        menu_relatorio_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatorio_vendasActionPerformed(evt);
            }
        });
        jMenu6.add(menu_relatorio_vendas);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Configuração");

        menu_troca_usuarios.setText("Tocar de Usuário");
        menu_troca_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_troca_usuariosActionPerformed(evt);
            }
        });
        jMenu5.add(menu_troca_usuarios);

        jMenuBar1.add(jMenu5);

        menu_sair.setText("Sair");
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1061, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clienteActionPerformed
        // Menu cliente
        Frmcliente tela = new Frmcliente();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_clienteActionPerformed

    private void menu_relatorio_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatorio_vendasActionPerformed
        // Menu relatório vendas
        Frmrelatorio tela = new Frmrelatorio();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_relatorio_vendasActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Tela em fullscreen
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void menu_troca_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_troca_usuariosActionPerformed
        // Trocar de usuário
        Frmmenu telamenu = new Frmmenu();
        telamenu.setVisible(false);
        Frmlogin telalogin = new Frmlogin();
        telalogin.setVisible(true);
    }//GEN-LAST:event_menu_troca_usuariosActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        // Botão sair
        int op;
        op = JOptionPane.showConfirmDialog(null, "Você realmente quer sair?");
        if(op==0) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_menu_sairMouseClicked

    private void menu_consulta_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consulta_produtosActionPerformed
        // Menu consultar produto
        Frmproduto tela = new Frmproduto();
        tela.jTabbedPane1.setSelectedIndex(1);
        tela.setVisible(true);
    }//GEN-LAST:event_menu_consulta_produtosActionPerformed

    private void menu_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_usuariosActionPerformed
        // Menu usuários
        Frmusuario tela = new Frmusuario();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_usuariosActionPerformed

    private void menu_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fornecedoresActionPerformed
        // Menu fornecedores
        Frmfornecedor tela = new Frmfornecedor();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_fornecedoresActionPerformed

    private void menu_ponto_pendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ponto_pendaActionPerformed
        // Menu pdv
        Frmvendas tela = new Frmvendas();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_ponto_pendaActionPerformed

    private void menu_posicao_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_posicao_diaActionPerformed
        // Menu posição do dia
        Frmtotalvendas tela = new Frmtotalvendas();
        tela.setVisible(true);
    }//GEN-LAST:event_menu_posicao_diaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Frmestoque tela = new Frmestoque();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem menu_cliente;
    private javax.swing.JMenuItem menu_consulta_produtos;
    private javax.swing.JMenuItem menu_fornecedores;
    private javax.swing.JMenuItem menu_ponto_penda;
    public javax.swing.JMenuItem menu_posicao_dia;
    public javax.swing.JMenuItem menu_relatorio_vendas;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenuItem menu_troca_usuarios;
    private javax.swing.JMenuItem menu_usuarios;
    // End of variables declaration//GEN-END:variables

}

