/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ItensPedidosDao;
import dao.PedidosDao;
import dao.ProdutosDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;
import model.ItensPedidos;
import model.Pedidos;
import model.Produtos;

/**
 *
 * @author ANDRADE
 */
public class Frmpagamentos extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Clientes cliente = new Clientes();
	DefaultTableModel carrinho;

	/**
	 * Creates new form Frmpagamentos
	 */
	public Frmpagamentos() {
		initComponents();

		// iniciar valor com 0
		txtcartao.setText("0");
		txtdinheiro.setText("0");
		txttroco.setText("0");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtdinheiro = new javax.swing.JTextField();
		txtcartao = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txttroco = new javax.swing.JTextField();
		txttotal = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		btnfinalizar = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtobs = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Forma de Pagamento");

		jPanel1.setBackground(new java.awt.Color(0, 153, 51));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Forma de Pagamento");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(240, 240, 240).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel2.setText("Dinheiro:");

		txtdinheiro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		txtdinheiro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtdinheiroActionPerformed(evt);
			}
		});

		txtcartao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		txtcartao.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtcartaoActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel3.setText("Cartão:");

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel4.setText("Troco:");

		txttroco.setEditable(false);
		txttroco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		txttroco.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txttrocoActionPerformed(evt);
			}
		});

		txttotal.setEditable(false);
		txttotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		txttotal.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txttotalActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel5.setText("Valor Total:");

		btnfinalizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		btnfinalizar.setText("Finalizar Venda");
		btnfinalizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnfinalizarActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel6.setText("Obs.:");

		txtobs.setColumns(20);
		txtobs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		txtobs.setRows(5);
		jScrollPane1.setViewportView(txtobs);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(50, 50, 50)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(txtdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 209,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(txtcartao, javax.swing.GroupLayout.PREFERRED_SIZE, 209,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5).addComponent(jLabel4))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txttroco, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 209,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 209,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(18, 18, 18).addComponent(jLabel6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(279, 279, 279)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
								.addComponent(txtdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6)).addGap(40, 40, 40)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(txtcartao, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(40, 40, 40)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4)
										.addComponent(txttroco, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(40, 40, 40)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel5).addComponent(txttotal,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
				.addComponent(btnfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(23, 23, 23)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void txtdinheiroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtdinheiroActionPerformed

	}// GEN-LAST:event_txtdinheiroActionPerformed

	private void txtcartaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtcartaoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtcartaoActionPerformed

	private void txttrocoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txttrocoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txttrocoActionPerformed

	private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txttotalActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txttotalActionPerformed

	private void btnfinalizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnfinalizarActionPerformed
		// Botão finalizar pedido

		double pcartao, pdinheiro, totalpago = 0, totalvenda, troco;
		pcartao = Double.parseDouble(txtcartao.getText());
		pdinheiro = Double.parseDouble(txtdinheiro.getText());

		totalvenda = Double.parseDouble(txttotal.getText());

		// Calcularo total e o troco
		totalpago = pcartao + pdinheiro;
		troco = totalpago - totalvenda;

		txttroco.setText(String.valueOf(troco));

		Pedidos objp = new Pedidos();

		// objeto cliente pengando o valor do id
		objp.setCliente(cliente);

		// Carrega a data atual do sistema
		Date agora = new Date();
		SimpleDateFormat dataEUA = new SimpleDateFormat("yyyy-MM-dd");
		String datamysql = dataEUA.format(agora);

		objp.setData_venda(datamysql);

		// Total da pedido
		objp.setTotal_venda(totalvenda);

		// Observação
		objp.setObs(txtobs.getText());

		// Cadastrar pedido
		PedidosDao dao_p = new PedidosDao();
		dao_p.cadastrarPedido(objp);

		// Retorna o id da ultima venda realizada
		objp.setId(dao_p.retornaUltimoPedido());

		// Cadastrando os produtos na tabela itemvendas
		for (int i = 0; i < carrinho.getRowCount(); i++) {

			int qtd_estoque, qtd_comprada, qtd_atualizada;
			Produtos objpr = new Produtos();
			ProdutosDao dao_prodto = new ProdutosDao();
			ItensPedidos item = new ItensPedidos();
			item.setVenda(objp);

			objpr.setId(Integer.parseInt(carrinho.getValueAt(i, 0).toString()));
			item.setProduto(objpr);
			item.setQtd(Integer.parseInt(carrinho.getValueAt(i, 2).toString()));
			item.setSubtotal(Double.parseDouble(carrinho.getValueAt(i, 4).toString()));

			// Baixa no estoque
			qtd_estoque = dao_prodto.retornaEstoqueAtual(objpr.getId());
			qtd_comprada = Integer.parseInt(carrinho.getValueAt(i, 2).toString());
			qtd_atualizada = qtd_estoque - qtd_comprada;

			dao_prodto.baixaEstoque(objpr.getId(), qtd_atualizada);

			ItensPedidosDao daoitem = new ItensPedidosDao();
			daoitem.cadastraItem(item);

		}
		/***********************************************************************/

		JOptionPane.showMessageDialog(null, "Venda Registrada com Sucesso!");

//        if(totalpago >= totalvenda) {
//            //Cadastrar pedido
//            PedidosDao dao_p = new PedidosDao();
//            dao_p.cadastrarPedido(objp);
//            
//        } else {
//            JOptionPane.showMessageDialog(null, "Valor pago não pode ser menor que o valor total do pedido.");
//            txttroco.setText(String.valueOf(troco));
//        }

	}// GEN-LAST:event_btnfinalizarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frmpagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frmpagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frmpagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frmpagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frmpagamentos().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnfinalizar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField txtcartao;
	private javax.swing.JTextField txtdinheiro;
	private javax.swing.JTextArea txtobs;
	public javax.swing.JTextField txttotal;
	private javax.swing.JTextField txttroco;
	// End of variables declaration//GEN-END:variables
}
